---
abstract: 'interface to Journyx'
author:
  - '=head1 CONTRIBUTORS'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::MockObject: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Journyx
no_index:
  directory:
    - inc
    - t
recommends:
  DateTime: 0
requires:
  LWP::UserAgent: 0
  Moose: 0.50
  MooseX::Role::Parameterized: 0.03
  URI: 0
  XML::Compile: 0
  XML::Compile::SOAP: 0
version: 0.11
